"use client";

import { useRef, useState, type CSSProperties, type FormEvent } from "react";
import { Bookmark, BookOpen, CalendarDays, ImagePlus, MessageCircle, Palette, Shield, ShoppingBag, Sparkles, Users } from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { toast } from "sonner";

type Viewer = { id:string; name:string; email:string } | null;
type ProfileTab = "home" | "diary" | "records";
type ProfileDetails = { name:string; intro:string; status:string; tags:string[] };
type ProfilePost = { id:string; title:string; body:string; community:string; kind:string; time:string; comments:number; author:string; likes?:number; liked?:boolean; saved?:boolean; mine?:boolean };
type RoomSettings = { backgroundImage:string; backgroundPosition:"top"|"center"|"bottom"; homeTitle:string; roomLabel:string; roomTitle:string; roomDescription:string; textTone:"light"|"dark"; overlayStyle:"none"|"light"|"dark" };

const defaultRoom:RoomSettings={backgroundImage:"",backgroundPosition:"center",homeTitle:"나의 작은 취향 공간",roomLabel:"오늘의 취향",roomTitle:"좋아하는 장면을 오래 간직하는 방",roomDescription:"최근에는 프리렌의 조용한 장면들과 듄의 세계관을 다시 보고 있어요.",textTone:"dark",overlayStyle:"light"};

const diaries = [
  { date:"09.24", title:"프리렌 28화 엔딩 이후의 표정 이야기", body:"말보다 오래 남았던 마지막 표정과 장면을 천천히 다시 보았다." },
  { date:"09.22", title:"듄 원작과 영화의 장면을 나란히 보기", body:"같은 장면이 문장과 화면에서 어떻게 다르게 느껴지는지 기록했다." },
  { date:"09.19", title:"폰타인 퀘스트에서 다시 발견한 복선", body:"처음에는 지나쳤던 대사들이 결말을 알고 나니 새롭게 보였다." },
];
const records = [
  { work:"장송의 프리렌", kind:"회차 감상", date:"2026.09.24" },
  { work:"듄", kind:"원작·영화 비교", date:"2026.09.22" },
  { work:"푸리나 · 원신", kind:"인물 기록", date:"2026.09.19" },
  { work:"데미안", kind:"문장 수집", date:"2026.09.14" },
];

export function FandomProfile({user,signInPath,signOutPath,openMessages,openSection,joinedCount,posts}:{user:Viewer;signInPath:string;signOutPath:string;openMessages:()=>void;openSection:(section:"mine"|"activities"|"market")=>void;joinedCount:number;posts:ProfilePost[]}) {
  const [decorating,setDecorating]=useState(false);
  const [activeTab,setActiveTab]=useState<ProfileTab>("home");
  const [editing,setEditing]=useState(false);
  const [followDialog,setFollowDialog]=useState<"following"|"friends"|null>(null);
  const [recordFilter,setRecordFilter]=useState<"mine"|"liked"|"saved">("mine");
  const roomImageRef=useRef<HTMLInputElement>(null);
  const [initialStyle]=useState(()=>{if(typeof window==="undefined")return {accent:"#5a82d7",pattern:"dot",frame:"classic"};try{return JSON.parse(localStorage.getItem("mini-home-style")||"null")||{accent:"#5a82d7",pattern:"dot",frame:"classic"}}catch{return {accent:"#5a82d7",pattern:"dot",frame:"classic"}}});
  const [accent]=useState(initialStyle.accent);
  const [pattern]=useState(initialStyle.pattern);
  const [frame]=useState(initialStyle.frame);
  const [initialRoom]=useState<RoomSettings>(()=>{const fallback={...defaultRoom,homeTitle:`${user?.name||"나"}의 작은 취향 공간`};if(typeof window==="undefined")return fallback;try{return {...fallback,...JSON.parse(localStorage.getItem("mini-home-room")||"null")}}catch{return fallback}});
  const [room,setRoom]=useState<RoomSettings>(initialRoom);
  const [roomDraft,setRoomDraft]=useState<RoomSettings>(initialRoom);
  const [roomError,setRoomError]=useState("");
  const defaultProfile:ProfileDetails={name:user?.name||"",intro:"이야기가 오래 남는 작품과 인물을 천천히 기록해요.",status:"오늘도 좋아하는 것을 오래 보기",tags:["프리렌","듄","원신","데미안"]};
  const [profile,setProfile]=useState<ProfileDetails>(defaultProfile);
  const [draft,setDraft]=useState<ProfileDetails>(defaultProfile);
  const openDecor=()=>{setRoomDraft(room);setRoomError("");setDecorating(true)};
  const cancelDecor=()=>{setRoomDraft(room);setRoomError("");setDecorating(false)};
  const saveDecor=()=>{try{localStorage.setItem("mini-home-style",JSON.stringify({accent,pattern,frame}));localStorage.setItem("mini-home-room",JSON.stringify(roomDraft));setRoom(roomDraft);setDecorating(false);toast.success("내 덕질방 꾸미기를 저장했어요")}catch{setRoomError("브라우저 저장 공간이 부족해요. 더 작은 사진을 선택해 주세요.")}};
  const pickRoomImage=(file?:File)=>{if(!file)return;setRoomError("");if(!["image/jpeg","image/png","image/webp"].includes(file.type)){setRoomError("JPG, PNG, WebP 이미지만 사용할 수 있어요.");return;}if(file.size>5_000_000){setRoomError("배경 이미지는 5MB 이하로 선택해 주세요.");return;}const objectUrl=URL.createObjectURL(file);const image=new Image();image.onload=()=>{const scale=Math.min(1,1600/image.width,900/image.height);const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));canvas.getContext("2d")?.drawImage(image,0,0,canvas.width,canvas.height);const backgroundImage=canvas.toDataURL("image/webp",.82);URL.revokeObjectURL(objectUrl);if(backgroundImage.length>1_200_000){setRoomError("압축 후에도 이미지가 너무 커요. 더 작은 사진을 선택해 주세요.");return;}setRoomDraft(value=>({...value,backgroundImage}));};image.onerror=()=>{URL.revokeObjectURL(objectUrl);setRoomError("이미지를 불러오지 못했어요.")};image.src=objectUrl};
  const openProfileEditor=()=>{setDraft({...profile,tags:[...profile.tags]});setEditing(true)};
  const saveProfile=(event:FormEvent)=>{event.preventDefault();const name=draft.name.trim();if(!name){toast.error("표시 이름을 입력해 주세요");return;}setProfile({...draft,name,tags:draft.tags.filter(Boolean)});setEditing(false);toast.success("프로필을 저장했어요")};
  if(!user) return <div className="single-page profile-login"><h1>나만의 덕질 기록을 모아보세요</h1><p>로그인하면 최애 작품, 커뮤니티, 기록과 친구를 한곳에서 관리할 수 있어요.</p><a className="primary" href={signInPath} target="_top">로그인 / 회원가입</a></div>;
  const items=[[Users,"가입한 커뮤니티",`${joinedCount}개`],[BookOpen,"내가 쓴 글","8개"],[CalendarDays,"참여 중인 활동","2개"],[ShoppingBag,"거래 중인 굿즈","1개"]] as const;
  const myPosts=posts.filter(post=>post.mine||post.author===user.name);
  const visiblePosts=myPosts.length?myPosts:diaries.map((item,index)=>({id:`diary-${index}`,title:item.title,body:item.body,community:"내 덕질 기록",kind:"기록",time:item.date,comments:12,author:user.name,mine:true}));
  const recordPosts=recordFilter==="mine"?visiblePosts:posts.filter(post=>recordFilter==="liked"?post.liked:post.saved);
  const style={"--mini-accent":accent} as CSSProperties;
  const visibleRoom=decorating?roomDraft:room;
  const roomStyle={backgroundImage:visibleRoom.backgroundImage?`url(${JSON.stringify(visibleRoom.backgroundImage)})`:undefined,backgroundPosition:visibleRoom.backgroundPosition} as CSSProperties;
  return <div className={`single-page profile-page mini-home pattern-${pattern} frame-${frame}`} style={style}>
    <header className="mini-home-top"><div className="visit-counter"><small>TODAY</small><b>024</b><i/><small>TOTAL</small><b>12,948</b></div><div className="mini-home-title"><h1>{visibleRoom.homeTitle}</h1></div><div className="mini-home-mood"><button className="decorate-button" onClick={openDecor}><Sparkles/> 꾸미기</button></div></header>
    {decorating&&<section className="decorate-panel room-decor-panel" aria-label="내 덕질방 꾸미기"><header><div><b>내 덕질방 꾸미기</b><p>좋아하는 작품이나 장면으로 나만의 공간을 꾸며보세요.</p></div></header><div className="room-decor-grid"><fieldset><legend>내 덕질방 배경</legend><input ref={roomImageRef} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>pickRoomImage(event.target.files?.[0])}/><div className="room-image-actions"><button className="outline" type="button" onClick={()=>roomImageRef.current?.click()}><ImagePlus/>{roomDraft.backgroundImage?"사진 변경":"사진 선택"}</button>{roomDraft.backgroundImage&&<button type="button" onClick={()=>setRoomDraft(value=>({...value,backgroundImage:""}))}>사진 제거</button>}</div><small>JPG, PNG, WebP · 원본 5MB 이하</small><label>배경 위치<select value={roomDraft.backgroundPosition} onChange={event=>setRoomDraft(value=>({...value,backgroundPosition:event.target.value as RoomSettings["backgroundPosition"]}))}><option value="top">위</option><option value="center">가운데</option><option value="bottom">아래</option></select></label></fieldset><fieldset><legend>덕질방 문구</legend><label>미니홈피 제목<input maxLength={40} value={roomDraft.homeTitle} onChange={event=>setRoomDraft(value=>({...value,homeTitle:event.target.value}))}/><small>{roomDraft.homeTitle.length}/40</small></label><label>오늘의 라벨<input maxLength={20} value={roomDraft.roomLabel} onChange={event=>setRoomDraft(value=>({...value,roomLabel:event.target.value}))}/><small>{roomDraft.roomLabel.length}/20</small></label><label>메인 문구<input maxLength={40} value={roomDraft.roomTitle} onChange={event=>setRoomDraft(value=>({...value,roomTitle:event.target.value}))}/><small>{roomDraft.roomTitle.length}/40</small></label><label>소개<textarea maxLength={100} value={roomDraft.roomDescription} onChange={event=>setRoomDraft(value=>({...value,roomDescription:event.target.value}))}/><small>{roomDraft.roomDescription.length}/100</small></label></fieldset><fieldset><legend>사진 위 가독성</legend><label>텍스트<select value={roomDraft.textTone} onChange={event=>setRoomDraft(value=>({...value,textTone:event.target.value as RoomSettings["textTone"]}))}><option value="dark">어둡게</option><option value="light">밝게</option></select></label><label>배경 효과<select value={roomDraft.overlayStyle} onChange={event=>setRoomDraft(value=>({...value,overlayStyle:event.target.value as RoomSettings["overlayStyle"]}))}><option value="none">없음</option><option value="light">밝게</option><option value="dark">어둡게</option></select></label></fieldset></div>{roomError&&<p className="form-error">{roomError}</p>}<footer><span>아래 덕질방에서 미리보기를 확인할 수 있어요.</span><div><button className="outline" type="button" onClick={cancelDecor}>취소</button><button className="primary" type="button" onClick={saveDecor}>저장</button></div></footer></section>}
    <div className="mini-home-body"><aside className="mini-profile-panel"><span className="panel-label">PROFILE</span><span className="avatar lg">{profile.name[0]}</span><h2>{profile.name}</h2><small>@taste_friend</small><p>{profile.intro}</p><div className="interest-tags">{profile.tags.map(tag=><span key={tag}>{tag}</span>)}</div><section className="profile-follow-summary" aria-label="팔로우와 친구"><button type="button" onClick={()=>setFollowDialog("following")}><b>4</b><span>팔로잉</span></button><button type="button" onClick={()=>setFollowDialog("friends")}><b>2</b><span>친구</span></button></section><button className="outline" onClick={openProfileEditor}>프로필 편집</button></aside>
      <main className="mini-main">
      {activeTab==="home"&&<><section className={`mini-feature tone-${visibleRoom.textTone} overlay-${visibleRoom.overlayStyle} ${visibleRoom.backgroundImage?"has-room-image":""}`} style={roomStyle}><div className="room-overlay"/><div className="room-content"><span className="panel-label">TODAY&apos;S ROOM</span><div className="feature-copy"><small>{visibleRoom.roomLabel}</small><h2>{visibleRoom.roomTitle}</h2><p>{visibleRoom.roomDescription}</p></div><div className="mini-shelf">{profile.tags.map(tag=><span key={tag}>{tag}</span>)}</div></div></section><section className="mini-post-feed"><header><span className="panel-label">MY POSTS</span><button onClick={()=>setActiveTab("diary")}>내가 쓴 글 전체 보기</button></header>{visiblePosts.slice(0,3).map(post=><article key={post.id}><time>{post.time}</time><div><small>{post.community} · {post.kind}</small><b>{post.title}</b><p>{post.body}</p><span>댓글 {post.comments}</span></div></article>)}</section></>}
      {activeTab==="diary"&&<section className="mini-post-feed mini-tab-list"><header><span className="panel-label">MY POSTS</span><p>내가 커뮤니티에 남긴 글</p></header>{visiblePosts.map(post=><article key={post.id}><time>{post.time}</time><div><small>{post.community} · {post.kind}</small><b>{post.title}</b><p>{post.body}</p><span>댓글 {post.comments}</span></div></article>)}</section>}
      {activeTab==="records"&&<section className="mini-diary mini-tab-list"><header><span className="panel-label">TASTE RECORDS</span><div className="record-filter-tabs"><button type="button" className={recordFilter==="mine"?"active":""} onClick={()=>setRecordFilter("mine")}>내 기록</button><button type="button" className={recordFilter==="liked"?"active":""} onClick={()=>setRecordFilter("liked")}>좋아요</button><button type="button" className={recordFilter==="saved"?"active":""} onClick={()=>setRecordFilter("saved")}>북마크</button></div></header>{recordPosts.length?recordPosts.map(post=><article key={post.id}><time>{post.time}</time><div><b>{post.community}</b><p>{post.title}</p><small>{recordFilter==="liked"?`좋아요 ${post.likes||0}`:recordFilter==="saved"?"북마크한 글":post.kind}</small></div></article>):<p className="record-empty">아직 {recordFilter==="liked"?"좋아요한":recordFilter==="saved"?"북마크한":"기록한"} 글이 없어요.</p>}</section>}
      </main>
      <nav className="mini-menu" aria-label="미니홈피 메뉴">{[["home","홈"],["diary","내 글"],["records","기록"]].map(([id,label])=><button key={id} aria-current={activeTab===id?"page":undefined} className={activeTab===id?"active":""} onClick={()=>setActiveTab(id as ProfileTab)}>{label}</button>)}</nav></div>
    <nav className="mini-utility-menu" aria-label="마이페이지 바로가기">{items.map(([Icon,label,count])=><button key={label} onClick={()=>{if(label==="가입한 커뮤니티")openSection("mine");else if(label==="참여 중인 활동")openSection("activities");else if(label==="거래 중인 굿즈")openSection("market");else setActiveTab("records")}}><Icon/><span>{label}</span><b>{count}</b></button>)}<button onClick={openMessages}><MessageCircle/><span>친구 대화</span><b>3</b></button></nav>
    <div className="profile-bottom"><button onClick={()=>toast("차단·신고 관리 화면입니다")}><Shield/> 차단·신고 관리</button><a href={signOutPath} target="_top">로그아웃</a></div>
    <Dialog open={followDialog!==null} onOpenChange={open=>!open&&setFollowDialog(null)}><DialogContent className="profile-follow-dialog"><DialogHeader><DialogTitle>{followDialog==="following"?"팔로잉":"친구"}</DialogTitle></DialogHeader>{followDialog==="following"?<div className="follow-dialog-list">{["장송의 프리렌","듄","원신","하야미 사오리"].map((name,index)=><div className="followed-work" key={name}><span>{name[0]}</span><div><b>{name}</b><small>{index===3?"성우":"새 기록이 도착했어요"}</small></div></div>)}</div>:<div className="follow-dialog-list"><div className="friend-preview"><span className="avatar sm">모</span><span><b>모카별</b><small>“새 글 잘 읽었어요!”</small></span><button className="primary">수락</button></div><div className="friend-preview"><span className="avatar sm">윤</span><span><b>윤슬</b><small>공통 최애 · 푸리나</small></span><button className="outline" onClick={openMessages}>대화</button></div></div>}</DialogContent></Dialog>
    <Dialog open={editing} onOpenChange={setEditing}><DialogContent className="profile-editor"><DialogHeader><DialogTitle>프로필 편집</DialogTitle></DialogHeader><form onSubmit={saveProfile}><label>표시 이름<input value={draft.name} onChange={event=>setDraft(value=>({...value,name:event.target.value}))}/></label><label>프로필 소개<textarea value={draft.intro} onChange={event=>setDraft(value=>({...value,intro:event.target.value}))}/></label><label>상태 메시지<input value={draft.status} onChange={event=>setDraft(value=>({...value,status:event.target.value}))}/></label><label>관심 태그<input value={draft.tags.join(", ")} onChange={event=>setDraft(value=>({...value,tags:event.target.value.split(",").map(tag=>tag.trim())}))} placeholder="쉼표로 구분"/></label><div><button className="outline" type="button" onClick={()=>setEditing(false)}>취소</button><button className="primary" type="submit">저장</button></div></form></DialogContent></Dialog>
  </div>;
}

export function FandomPublicProfile({name,openMessages,requireLogin}:{name:string;openMessages:()=>void;requireLogin:(action:()=>void)=>void}) {
  return <div className="single-page person-page"><header className="public-profile-head"><span className="avatar lg">{name[0]}</span><div><small>@blue_fandom</small><h1>{name}</h1><p>좋아하는 장면과 세계관을 오래 기록하고 있어요.</p><div className="interest-tags"><span>장송의 프리렌</span><span>듄</span><span>원신</span></div></div><div className="profile-actions"><button className="primary" onClick={()=>requireLogin(()=>toast.success("친구 요청을 보냈어요"))}><Users/> 친구 요청</button><button className="outline" onClick={openMessages}><MessageCircle/> 대화 시작</button><button className="icon-only" aria-label="사용자 차단"><Shield/></button></div></header><div className="relationship-summary"><div><b>3개</b><span>공통 작품</span></div><div><b>1명</b><span>공통 최애</span></div><div><b>2개</b><span>함께 가입한 커뮤니티</span></div></div><section className="public-records"><h2>{name}님의 공개 덕질 기록</h2>{[["듄","폴이 물을 마시는 장면, 원작과 달라진 의미"],["장송의 프리렌","28화 엔딩 이후 프리렌 표정 이야기"],["원신","폰타인 퀘스트 이후 다시 보이는 복선"]].map(([work,title])=><article key={title}><span className="kind">기록</span><div><small>{work} · 공개 덕질 기록</small><h3>{title}</h3></div></article>)}</section></div>;
}
