"use client";

import { useRef, useState } from "react";
import { ImagePlus, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";

type Viewer={id:string;name:string;email:string}|null;
type NewPost={id:string;title:string;author:string;handle:string;avatar:string;community:string;kind:string;body:string;time:string;image?:string;likes:number;comments:number;tags:string[];mine?:boolean};

export function FandomComposer({boardName,open,setOpen,user,onAdd}:{boardName:string;open:boolean;setOpen:(open:boolean)=>void;user:Viewer;onAdd:(post:NewPost)=>void}) {
  const [title,setTitle]=useState(""); const [body,setBody]=useState(""); const [anonymous,setAnonymous]=useState(false); const [kind,setKind]=useState("감상"); const [related,setRelated]=useState(""); const [progress,setProgress]=useState(""); const [warning,setWarning]=useState(""); const [spoiler,setSpoiler]=useState(false); const [images,setImages]=useState<string[]>([]); const [error,setError]=useState(""); const [loading,setLoading]=useState(false); const fileRef=useRef<HTMLInputElement>(null); const fanwork=boardName.startsWith("2차창작");
  const pick=(files:FileList|null)=>{if(!files)return;const list=Array.from(files).slice(0,4);if(list.some(f=>f.size>5_000_000)){setError("이미지는 한 장당 5MB 이하로 올려주세요.");return;}Promise.all(list.map(f=>new Promise<string>(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.readAsDataURL(f)}))).then(setImages)};
  const submit=async()=>{if(!title.trim()){setError("제목을 입력해 주세요.");return;}if(!body.trim()&&!images.length){setError("내용이나 이미지 중 하나는 꼭 넣어주세요.");return;}setLoading(true);setError("");try{const response=await fetch("/api/posts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title:title.trim(),body:body.trim(),community:boardName,kind,images:[],tags:["#덕질기록"],anonymous,related,progress,spoiler,warning})});if(!response.ok)throw new Error("save failed");onAdd({id:crypto.randomUUID(),title:title.trim(),author:anonymous?"익명":user?.name||"나",handle:anonymous?"":"@me",avatar:anonymous?"익":user?.name||"나",community:boardName,kind,body:body.trim(),time:"방금",image:images[0],likes:0,comments:0,tags:["#덕질기록"],mine:true});setTitle("");setBody("");setImages([]);setAnonymous(false)}catch{setError("업로드하지 못했어요. 잠시 후 다시 시도해 주세요.")}finally{setLoading(false)}};
  return <Dialog open={open} onOpenChange={setOpen}><DialogContent className="composer"><DialogHeader><DialogTitle>{boardName}에 글쓰기</DialogTitle></DialogHeader><p className="composer-board">커뮤니티 · <b>{boardName}</b></p><Input value={title} onChange={e=>setTitle(e.target.value)} placeholder="제목을 입력하세요"/><div className="composer-fields"><Input value={related} onChange={e=>setRelated(e.target.value)} placeholder={fanwork?"원작명":"관련 작품·인물"}/><Input value={progress} onChange={e=>setProgress(e.target.value)} placeholder={fanwork?"캐릭터 또는 대상":"회차·챕터·진행 구간 (선택)"}/></div><div className="anonymous-toggle"><span><b>스포일러 포함</b><small>목록에서 제목과 미리보기가 가려져요.</small></span><Switch checked={spoiler} onCheckedChange={setSpoiler}/></div>{spoiler&&<Input value={warning} onChange={e=>setWarning(e.target.value)} placeholder="예: 애니 28화 이후 내용 포함"/>}<div className="anonymous-toggle"><span><b>익명으로 작성</b><small>다른 사용자에게는 닉네임 대신 익명으로 표시돼요.</small></span><Switch checked={anonymous} onCheckedChange={setAnonymous}/></div><select className="kind-select" value={kind} onChange={e=>setKind(e.target.value)}>{["잡담","감상","후기","질문","정보","해석","앓는 글","작품","스포일러"].map(x=><option key={x}>{x}</option>)}</select><Textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="좋아하는 마음과 생각을 자유롭게 남겨보세요…"/><div className="preview-strip">{images.map((src,i)=><span key={src}><img src={src} alt={`첨부 이미지 ${i+1}`}/><button onClick={()=>setImages(v=>v.filter((_,n)=>n!==i))}><X/></button></span>)}</div>{error&&<p className="form-error">{error}</p>}<div className="composer-bottom"><input ref={fileRef} hidden type="file" multiple accept="image/*" onChange={e=>pick(e.target.files)}/><button className="attach" onClick={()=>fileRef.current?.click()}><ImagePlus/> 사진 <small>{images.length}/4</small></button><Button onClick={submit} disabled={loading}>{loading?"올리는 중…":"게시하기"}</Button></div></DialogContent></Dialog>;
}
