"use client";

import { Bookmark, BookOpen, CalendarDays, ChevronRight, MessageCircle, Palette, Shield, ShoppingBag, Star, Users } from "lucide-react";
import { toast } from "sonner";

type Viewer = { id:string; name:string; email:string } | null;

export function FandomProfile({user,signInPath,signOutPath,openMessages}:{user:Viewer;signInPath:string;signOutPath:string;openMessages:()=>void}) {
  if(!user) return <div className="single-page profile-login"><h1>나만의 덕질 기록을 모아보세요</h1><p>로그인하면 최애 작품, 덕질방, 기록과 덕친을 한곳에서 관리할 수 있어요.</p><a className="primary" href={signInPath} target="_top">로그인 / 회원가입</a></div>;
  const items=[[Users,"가입한 덕질방","2개"],[BookOpen,"덕질 기록","8개"],[Palette,"2차창작","3개"],[Bookmark,"북마크","24개"],[CalendarDays,"참여 중인 활동","2개"],[ShoppingBag,"거래 중인 굿즈","1개"]] as const;
  return <div className="single-page profile-page"><header className="profile-hero"><span className="avatar lg">{user.name[0]}</span><div><small>@taste_friend</small><h1>{user.name}</h1><p>이야기가 오래 남는 작품과 인물을 천천히 기록해요.</p><div className="interest-tags"><span>최애 · 장송의 프리렌</span><span>듄</span><span>원신</span><span>데미안</span></div></div><button className="outline">프로필 편집</button></header><button className="big-chat" onClick={openMessages}><span><MessageCircle/><b>덕친과 대화하기</b></span><span>읽지 않은 대화 3개 <ChevronRight/></span></button><div className="profile-grid"><section><h2>내 덕질</h2>{items.map(([Icon,label,count])=><button key={label}><Icon/><span>{label}</span><b>{count}</b><ChevronRight/></button>)}</section><section><h2>팔로우한 작품·인물</h2>{["장송의 프리렌","듄","원신","하야미 사오리"].map((name,i)=><div className="followed-work" key={name}><span>{name[0]}</span><div><b>{name}</b><small>{i===3?"성우":"새 기록이 도착했어요"}</small></div></div>)}</section><section><h2>덕친과 요청</h2><div className="friend-preview"><span className="avatar sm">모</span><span><b>모카별</b><small>공통 작품 3개 · 공통 덕질방 1개</small></span><button className="primary">수락</button></div><div className="friend-preview"><span className="avatar sm">윤</span><span><b>윤슬</b><small>공통 최애 · 푸리나</small></span><button className="outline" onClick={openMessages}>대화</button></div></section></div><div className="profile-bottom"><button onClick={()=>toast("차단·신고 관리 화면입니다")}><Shield/> 차단·신고 관리</button><a href={signOutPath} target="_top">로그아웃</a></div></div>;
}

export function FandomPublicProfile({name,openMessages}:{name:string;openMessages:()=>void}) {
  return <div className="single-page person-page"><header className="public-profile-head"><span className="avatar lg">{name[0]}</span><div><small>@blue_fandom</small><h1>{name}</h1><p>좋아하는 장면과 세계관을 오래 기록하고 있어요.</p><div className="interest-tags"><span>장송의 프리렌</span><span>듄</span><span>원신</span></div></div><div className="profile-actions"><button className="primary" onClick={()=>toast.success("덕친 요청을 보냈어요")}><Users/> 덕친 요청</button><button className="outline" onClick={openMessages}><MessageCircle/> 대화 시작</button><button className="icon-only" aria-label="사용자 차단"><Shield/></button></div></header><div className="relationship-summary"><div><b>3개</b><span>공통 작품</span></div><div><b>1명</b><span>공통 최애</span></div><div><b>2개</b><span>함께 가입한 덕질방</span></div></div><section className="public-records"><h2>{name}님의 공개 덕질 기록</h2>{[["듄","폴이 물을 마시는 장면, 원작과 달라진 의미"],["장송의 프리렌","28화 엔딩 이후 프리렌 표정 이야기"],["원신","폰타인 퀘스트 이후 다시 보이는 복선"]].map(([work,title])=><article key={title}><span className="kind">기록</span><div><small>{work} · 공개 덕질 기록</small><h3>{title}</h3></div></article>)}</section></div>;
}
