"use client";
import {useEffect,useMemo,useRef,useState,useSyncExternalStore,type CSSProperties} from "react";
import {createPortal} from "react-dom";
import {CloudSun} from "lucide-react";
type TimeMode="auto"|"morning"|"day"|"sunset"|"night"; type TimePhase=Exclude<TimeMode,"auto">;
type WeatherMode="auto"|"clear"|"cloudy"|"rain"|"snow"; type WeatherKind=Exclude<WeatherMode,"auto">|"storm"; type RGB=[number,number,number];
type BackgroundMode="light"|"solid"|"mood";
const TIME_KEY="chwihyang-ambient-time",WEATHER_KEY="chwihyang-ambient-weather",BACKGROUND_KEY="chwihyang-background-mode",SOLID_COLOR_KEY="chwihyang-solid-background",LEGACY_KEY="chwihyang-ambient-mood",CACHE_KEY="chwihyang-weather-cache";
const times:[TimeMode,string][]=[["auto","위치 자동"],["morning","아침"],["sunset","저녁"],["night","밤"]];
const weathers:[WeatherMode,string][]=[["clear","맑음"],["rain","비"],["snow","눈"]];
const backgrounds:[BackgroundMode,string][]=[["light","기본"],["solid","단색"],["mood","무드"]];
const fixedMinutes:Record<TimePhase,number>={morning:780,day:780,sunset:1110,night:1320};
const stops:{minute:number;top:RGB;bottom:RGB;glow:RGB}[]=[{minute:0,top:[22,30,75],bottom:[48,60,108],glow:[180,197,231]},{minute:300,top:[41,55,104],bottom:[196,130,139],glow:[255,199,148]},{minute:420,top:[112,170,214],bottom:[242,209,170],glow:[255,226,168]},{minute:600,top:[91,176,225],bottom:[210,237,243],glow:[255,241,189]},{minute:960,top:[82,161,218],bottom:[204,229,236],glow:[255,227,169]},{minute:1080,top:[112,111,173],bottom:[238,157,145],glow:[255,190,119]},{minute:1200,top:[54,58,117],bottom:[126,82,126],glow:[239,175,151]},{minute:1320,top:[24,32,81],bottom:[53,62,111],glow:[194,205,235]},{minute:1440,top:[22,30,75],bottom:[48,60,108],glow:[180,197,231]}];
const minutesNow=()=>{const d=new Date();return d.getHours()*60+d.getMinutes()};
const phase=(m:number):TimePhase=>m>=330&&m<660?"morning":m>=660&&m<1020?"day":m>=1020&&m<1200?"sunset":"night";
const color=(v:RGB)=>`rgb(${v.join(" ")})`; const mix=(a:number,b:number,t:number)=>Math.round(a+(b-a)*t);
function sky(m:number){let i=stops.findIndex(s=>s.minute>=m);i=Math.max(1,i);const a=stops[i-1],b=stops[i],t=Math.max(0,Math.min(1,(m-a.minute)/(b.minute-a.minute)));const blend=(k:"top"|"bottom"|"glow")=>color(a[k].map((v,n)=>mix(v,b[k][n],t)) as RGB);return{top:blend("top"),bottom:blend("bottom"),glow:blend("glow")}}
function weatherCode(code:number):WeatherKind{if(code===0)return"clear";if([71,73,75,77,85,86].includes(code))return"snow";if([51,53,55,56,57,61,63,65,66,67,80,81,82].includes(code))return"rain";if(code>=95)return"storm";return"cloudy"}
const validTime=(v:string|null):v is TimeMode=>times.some(([id])=>id===v),validWeather=(v:string|null):v is WeatherMode=>weathers.some(([id])=>id===v),validBackground=(v:string|null):v is BackgroundMode=>backgrounds.some(([id])=>id===v);
function initialTime():TimeMode{if(typeof window==="undefined")return"morning";const v=localStorage.getItem(TIME_KEY);if(validTime(v))return v;const current=phase(minutesNow());return current==="day"?"morning":current}
function initialWeather():WeatherMode{if(typeof window==="undefined")return"clear";const v=localStorage.getItem(WEATHER_KEY);if(validWeather(v))return v;const old=localStorage.getItem(LEGACY_KEY);return old==="rain"||old==="snow"?old:"clear"}
function initialBackground():BackgroundMode{if(typeof window==="undefined")return"light";const value=localStorage.getItem(BACKGROUND_KEY);return validBackground(value)?value:"light"}
function initialSolidColor(){return typeof window==="undefined"?"#cfe4ee":localStorage.getItem(SOLID_COLOR_KEY)||"#cfe4ee"}
function cached():WeatherKind|null{try{const c=JSON.parse(localStorage.getItem(CACHE_KEY)||"null") as {kind?:WeatherKind;at?:number}|null;if(c?.kind&&c.at&&Date.now()-c.at<1_800_000)return c.kind}catch{}return null}
export function WeatherAmbient(){
 const[timeMode,setTime]=useState<TimeMode>(initialTime),[weatherMode,setWeatherMode]=useState<WeatherMode>(initialWeather),[backgroundMode,setBackgroundMode]=useState<BackgroundMode>(initialBackground),[solidColor,setSolidColor]=useState(initialSolidColor),[weather,setWeather]=useState<WeatherKind>(()=>typeof window==="undefined"?"clear":cached()||"clear"),[now,setNow]=useState(minutesNow),[open,setOpen]=useState(false),[locationState,setLocation]=useState<"idle"|"loading"|"ready"|"denied"|"error">("idle");
 const mounted=useSyncExternalStore(()=>()=>{},()=>true,()=>false),menuRef=useRef<HTMLDivElement>(null),time=timeMode==="auto"?phase(now):timeMode,weatherKind=timeMode==="auto"?weather:weatherMode,colors=useMemo(()=>sky(timeMode==="auto"?now:fixedMinutes[timeMode]),[timeMode,now]);
 const fetchWeather=(lat:number,lon:number)=>{setLocation("loading");fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat.toFixed(3)}&longitude=${lon.toFixed(3)}&current=weather_code&timezone=auto&forecast_days=1`).then(r=>{if(!r.ok)throw Error();return r.json() as Promise<{current?:{weather_code?:number}}>}).then(d=>{if(typeof d.current?.weather_code!=="number")throw Error();const kind=weatherCode(d.current.weather_code);setWeather(kind);setLocation("ready");localStorage.setItem(CACHE_KEY,JSON.stringify({kind,at:Date.now()}))}).catch(()=>setLocation("error"))};
 const locate=()=>{if(!navigator.geolocation){setLocation("error");return}setLocation("loading");navigator.geolocation.getCurrentPosition(p=>fetchWeather(p.coords.latitude,p.coords.longitude),e=>setLocation(e.code===e.PERMISSION_DENIED?"denied":"error"),{timeout:8000,maximumAge:1_800_000})};
 useEffect(()=>{const id=window.setInterval(()=>setNow(minutesNow()),60_000);return()=>clearInterval(id)},[]);useEffect(()=>{document.documentElement.dataset.ambientTime=time;document.documentElement.dataset.ambientWeather=weatherKind;document.documentElement.dataset.backgroundMode=backgroundMode;if(backgroundMode!=="mood"){document.documentElement.dataset.theme="light";localStorage.setItem("chwihyang-theme","light")}},[time,weatherKind,backgroundMode]);
 // 위치 권한은 자동 날씨를 다시 선택할 때만 확인한다.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{if(timeMode!=="auto"||!("permissions"in navigator))return;navigator.permissions.query({name:"geolocation"}).then(()=>{if(navigator.geolocation)locate()}).catch(()=>{if(navigator.geolocation)locate()})},[timeMode]);useEffect(()=>{const close=(e:MouseEvent)=>{if(!menuRef.current?.contains(e.target as Node))setOpen(false)};document.addEventListener("mousedown",close);return()=>document.removeEventListener("mousedown",close)},[]);
 const chooseTime=(v:TimeMode)=>{setTime(v);localStorage.setItem(TIME_KEY,v);localStorage.removeItem(LEGACY_KEY)},chooseWeather=(v:WeatherMode)=>{setWeatherMode(v);localStorage.setItem(WEATHER_KEY,v);localStorage.removeItem(LEGACY_KEY);if(v!=="auto")setLocation("idle")},chooseBackground=(v:BackgroundMode)=>{setBackgroundMode(v);localStorage.setItem(BACKGROUND_KEY,v);document.documentElement.dataset.theme="light";localStorage.setItem("chwihyang-theme","light")},chooseSolidColor=(value:string)=>{setSolidColor(value);localStorage.setItem(SOLID_COLOR_KEY,value)};
 const count=weatherKind==="rain"||weatherKind==="snow"?22:time==="night"?18:8;
 const style={"--sky-top":colors.top,"--sky-bottom":colors.bottom,"--sky-glow":colors.glow,"--solid-background":solidColor} as CSSProperties;
 const scene=<div className={`weather-ambient background-${backgroundMode} weather-${weatherKind} time-${time}`} style={style} aria-hidden="true"><div className="ambient-sky"/><div className="ambient-glow"/><div className="ambient-horizon"/><div className="ambient-particles">{Array.from({length:count},(_,i)=><i key={i} style={{"--particle-index":i,"--particle-left":`${(i*37+11)%97}%`,"--particle-delay":`${-(i%9)*.7}s`} as CSSProperties}/>)}</div></div>;
 return <>{mounted&&createPortal(scene,document.body)}<div className="mood-control" ref={menuRef}><button className="mood-button" aria-label="배경 설정" onClick={()=>setOpen(v=>!v)} aria-expanded={open}><CloudSun/><span>배경</span></button>{open&&<div className="mood-menu" role="dialog" aria-label="배경 설정"><header><b>배경</b><small>원하는 바탕을 고르고, 무드에서는 날씨를 직접 설정할 수 있어요.</small></header><MoodGroup title="배경" items={backgrounds} value={backgroundMode} choose={chooseBackground}/>{backgroundMode==="solid"&&<label className="solid-background-picker">단색 선택<input type="color" value={solidColor} onChange={event=>chooseSolidColor(event.target.value)}/></label>}{backgroundMode==="mood"&&<><MoodGroup title="시간" items={times} value={timeMode} choose={chooseTime}/><MoodGroup title="날씨" items={weathers} value={weatherMode} choose={chooseWeather}/>{timeMode==="auto"&&<small className="auto-weather-status">{locationState==="loading"?"위치와 날씨를 확인하는 중…":locationState==="ready"?"현재 위치의 시간과 날씨를 반영 중이에요.":locationState==="denied"?"기기 시간과 기본 날씨를 사용 중이에요.":locationState==="error"?"날씨를 불러오지 못해 기본 날씨를 사용해요.":"위치 기반 시간과 날씨를 자동으로 반영해요."}</small>}</>}</div>}</div></>;
}
function MoodGroup<T extends string>({title,items,value,choose}:{title:string;items:[T,string][];value:T;choose:(v:T)=>void}){return <section className="mood-group"><strong>{title}</strong><div>{items.map(([id,label])=><button key={id} role="radio" aria-checked={value===id} className={value===id?"active":""} onClick={()=>choose(id)}><i/>{label}</button>)}</div></section>}
