"use client";
import {useEffect,useMemo,useRef,useState,useSyncExternalStore,type CSSProperties} from "react";
import {createPortal} from "react-dom";
import {CloudSun,MapPin} from "lucide-react";
type TimeMode="auto"|"morning"|"day"|"sunset"|"night"; type TimePhase=Exclude<TimeMode,"auto">;
type WeatherMode="auto"|"clear"|"cloudy"|"rain"|"snow"; type WeatherKind=Exclude<WeatherMode,"auto">|"storm"; type RGB=[number,number,number];
const TIME_KEY="chwihyang-ambient-time",WEATHER_KEY="chwihyang-ambient-weather",LEGACY_KEY="chwihyang-ambient-mood",CACHE_KEY="chwihyang-weather-cache";
const times:[TimeMode,string][]=[["morning","아침"],["sunset","저녁"],["night","밤"]];
const weathers:[WeatherMode,string][]=[["auto","위치 자동"],["clear","맑음"],["rain","비"],["snow","눈"]];
const fixedMinutes:Record<TimePhase,number>={morning:780,day:780,sunset:1110,night:1320};
const stops:{minute:number;top:RGB;bottom:RGB;glow:RGB}[]=[{minute:0,top:[22,30,75],bottom:[48,60,108],glow:[180,197,231]},{minute:300,top:[41,55,104],bottom:[196,130,139],glow:[255,199,148]},{minute:420,top:[112,170,214],bottom:[242,209,170],glow:[255,226,168]},{minute:600,top:[91,176,225],bottom:[210,237,243],glow:[255,241,189]},{minute:960,top:[82,161,218],bottom:[204,229,236],glow:[255,227,169]},{minute:1080,top:[112,111,173],bottom:[238,157,145],glow:[255,190,119]},{minute:1200,top:[54,58,117],bottom:[126,82,126],glow:[239,175,151]},{minute:1320,top:[24,32,81],bottom:[53,62,111],glow:[194,205,235]},{minute:1440,top:[22,30,75],bottom:[48,60,108],glow:[180,197,231]}];
const minutesNow=()=>{const d=new Date();return d.getHours()*60+d.getMinutes()};
const phase=(m:number):TimePhase=>m>=330&&m<660?"morning":m>=660&&m<1020?"day":m>=1020&&m<1200?"sunset":"night";
const color=(v:RGB)=>`rgb(${v.join(" ")})`; const mix=(a:number,b:number,t:number)=>Math.round(a+(b-a)*t);
function sky(m:number){let i=stops.findIndex(s=>s.minute>=m);i=Math.max(1,i);const a=stops[i-1],b=stops[i],t=Math.max(0,Math.min(1,(m-a.minute)/(b.minute-a.minute)));const blend=(k:"top"|"bottom"|"glow")=>color(a[k].map((v,n)=>mix(v,b[k][n],t)) as RGB);return{top:blend("top"),bottom:blend("bottom"),glow:blend("glow")}}
function weatherCode(code:number):WeatherKind{if(code===0)return"clear";if([71,73,75,77,85,86].includes(code))return"snow";if([51,53,55,56,57,61,63,65,66,67,80,81,82].includes(code))return"rain";if(code>=95)return"storm";return"cloudy"}
const validTime=(v:string|null):v is TimeMode=>times.some(([id])=>id===v),validWeather=(v:string|null):v is WeatherMode=>weathers.some(([id])=>id===v);
function initialTime():TimeMode{if(typeof window==="undefined")return"morning";const v=localStorage.getItem(TIME_KEY);if(validTime(v))return v;const current=phase(minutesNow());return current==="day"?"morning":current}
function initialWeather():WeatherMode{if(typeof window==="undefined")return"clear";const v=localStorage.getItem(WEATHER_KEY);if(validWeather(v))return v;const old=localStorage.getItem(LEGACY_KEY);return old==="rain"||old==="snow"?old:"clear"}
function cached():WeatherKind|null{try{const c=JSON.parse(localStorage.getItem(CACHE_KEY)||"null") as {kind?:WeatherKind;at?:number}|null;if(c?.kind&&c.at&&Date.now()-c.at<1_800_000)return c.kind}catch{}return null}
export function WeatherAmbient(){
 const[timeMode,setTime]=useState<TimeMode>(initialTime),[weatherMode,setWeatherMode]=useState<WeatherMode>(initialWeather),[weather,setWeather]=useState<WeatherKind>(()=>typeof window==="undefined"?"clear":cached()||"clear"),[now,setNow]=useState(minutesNow),[open,setOpen]=useState(false),[locationState,setLocation]=useState<"idle"|"loading"|"ready"|"denied"|"error">("idle");
 const mounted=useSyncExternalStore(()=>()=>{},()=>true,()=>false),menuRef=useRef<HTMLDivElement>(null),time=timeMode==="auto"?phase(now):timeMode,weatherKind=weatherMode==="auto"?weather:weatherMode,colors=useMemo(()=>sky(timeMode==="auto"?now:fixedMinutes[timeMode]),[timeMode,now]);
 const fetchWeather=(lat:number,lon:number)=>{setLocation("loading");fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat.toFixed(3)}&longitude=${lon.toFixed(3)}&current=weather_code&timezone=auto&forecast_days=1`).then(r=>{if(!r.ok)throw Error();return r.json() as Promise<{current?:{weather_code?:number}}>}).then(d=>{if(typeof d.current?.weather_code!=="number")throw Error();const kind=weatherCode(d.current.weather_code);setWeather(kind);setLocation("ready");localStorage.setItem(CACHE_KEY,JSON.stringify({kind,at:Date.now()}))}).catch(()=>setLocation("error"))};
 const locate=()=>{if(!navigator.geolocation){setLocation("error");return}setLocation("loading");navigator.geolocation.getCurrentPosition(p=>fetchWeather(p.coords.latitude,p.coords.longitude),e=>setLocation(e.code===e.PERMISSION_DENIED?"denied":"error"),{timeout:8000,maximumAge:1_800_000})};
 useEffect(()=>{const id=window.setInterval(()=>setNow(minutesNow()),60_000);return()=>clearInterval(id)},[]);useEffect(()=>{document.documentElement.dataset.ambientTime=time;document.documentElement.dataset.ambientWeather=weatherKind},[time,weatherKind]);
 // 위치 권한은 자동 날씨를 다시 선택할 때만 확인한다.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{if(weatherMode!=="auto"||!("permissions"in navigator))return;navigator.permissions.query({name:"geolocation"}).then(p=>{if(p.state==="granted")locate();else if(p.state==="denied")setLocation("denied")}).catch(()=>{})},[weatherMode]);useEffect(()=>{const close=(e:MouseEvent)=>{if(!menuRef.current?.contains(e.target as Node))setOpen(false)};document.addEventListener("mousedown",close);return()=>document.removeEventListener("mousedown",close)},[]);
 const chooseTime=(v:TimeMode)=>{setTime(v);localStorage.setItem(TIME_KEY,v);localStorage.removeItem(LEGACY_KEY)},chooseWeather=(v:WeatherMode)=>{setWeatherMode(v);localStorage.setItem(WEATHER_KEY,v);localStorage.removeItem(LEGACY_KEY);if(v!=="auto")setLocation("idle")};
 const count=weatherKind==="rain"||weatherKind==="snow"?22:time==="night"?18:8,style={"--sky-top":colors.top,"--sky-bottom":colors.bottom,"--sky-glow":colors.glow} as CSSProperties;
 const scene=<div className={`weather-ambient weather-${weatherKind} time-${time}`} style={style} aria-hidden="true"><div className="ambient-sky"/><div className="ambient-glow"/><div className="ambient-horizon"/><div className="ambient-particles">{Array.from({length:count},(_,i)=><i key={i} style={{"--particle-index":i,"--particle-left":`${(i*37+11)%97}%`,"--particle-delay":`${-(i%9)*.7}s`} as CSSProperties}/>)}</div></div>;
 return <>{mounted&&createPortal(scene,document.body)}<div className="mood-control" ref={menuRef}><button className="mood-button" onClick={()=>setOpen(v=>!v)} aria-expanded={open}><CloudSun/><span>무드</span></button>{open&&<div className="mood-menu" role="dialog" aria-label="오늘의 무드 설정"><header><b>오늘의 무드</b><small>시간과 날씨를 함께 골라 바깥 풍경을 꾸며요.</small></header><MoodGroup title="시간" items={times} value={timeMode} choose={chooseTime}/><MoodGroup title="날씨" items={weathers} value={weatherMode} choose={chooseWeather}/>{weatherMode==="auto"&&<div className="location-weather"><button onClick={locate} disabled={locationState==="loading"}><MapPin/>{locationState==="loading"?"날씨 확인 중…":"위치 날씨 사용"}</button>{locationState!=="idle"&&<small>{locationState==="ready"?"현재 날씨를 반영했어요.":locationState==="denied"?"위치 권한 없이 기본 날씨로 표시해요.":locationState==="error"?"날씨를 불러오지 못했어요.":""}</small>}</div>}</div>}</div></>;
}
function MoodGroup<T extends string>({title,items,value,choose}:{title:string;items:[T,string][];value:T;choose:(v:T)=>void}){return <section className="mood-group"><strong>{title}</strong><div>{items.map(([id,label])=><button key={id} role="radio" aria-checked={value===id} className={value===id?"active":""} onClick={()=>choose(id)}><i/>{label}</button>)}</div></section>}
